services:
  backend:
    build: ./backend
    ports: ['5000:5000']
    env_file: ./backend/.env
    depends_on: ['db']
  frontend:
    build: ./frontend
    ports: ['5173:3000']
    depends_on: ['backend']
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sush@postgres24
      POSTGRES_DB: comments_app
    volumes: ['db-data:/var/lib/postgresql/data']
volumes:
  db-data:
